# This is a basic workflow to help you get started with Actions

name: diagram-via-artifact

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v3
      - name: Repo Visualizer
        uses: githubocto/repo-visualizer@0.8.2
        with:
            output_file: "diagram.svg"
            excluded_paths: "dist,node_modules"
            artifact_name: "diagram generation"
            should_push: true
            branch: 'diagram'
            commit_message: 'updated diagram'

